all:
  hosts:
    localhost
  children:
    appbserver:
      hosts:
        localhost:
          java_package_name: openjdk-11-jdk
        <IP>:
          java_package_name: java-1.8.0-openjdk-devel
      vars:
        tomcat_version: "10.1.4"
        major_tomcat_version: "10"
        user_shell: /bin/false
        user_home: /opt/tomcat
        user_name: tomcat
        group_name: tomcat
        tomcat_service_name: tomcat.service
