---
- name: Intalling Utils
  hosts: all
  tasks:
    - name: installing Utils
      package:
        - name: "{{ item }}"
          state: present
      loop: "{{ packages }}"
      become: yes
    - name: debug variable
      debug:
        var: purpose